# -*- coding: utf-8 -*-
"""Exercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cowqCFt2xM_easOpzDrZO9PLoqdZZ9v2
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, learning_curve

dataset = pd.read_csv('../datasets/Dataset_3Cluster_4features.csv')

dataset.head()

dataset.describe()

X = dataset.drop(columns='V5').values
Y = dataset[['V5']].values.ravel()

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, stratify=Y, random_state=42)

"""## SKLearn"""

from sklearn.neural_network import MLPClassifier

clf1 = MLPClassifier(hidden_layer_sizes=(2), random_state=42, alpha=0, beta_1=0, beta_2=0, momentum=0, power_t=0, nesterovs_momentum=False)
clf1.fit(X_train, Y_train)

print('Remp: ', (1 - clf1.score(X_train, Y_train)), ' / Rest: ', (1 - clf1.score(X_test, Y_test)))
print('Remp - Rest: ', (1 - clf1.score(X_train, Y_train)) - (1 - clf1.score(X_test, Y_test)))

clf2 = MLPClassifier(hidden_layer_sizes=(2), learning_rate_init=0.1, random_state=42, alpha=0, beta_1=0, beta_2=0, momentum=0, power_t=0, nesterovs_momentum=False)
clf2.fit(X_train, Y_train)

print('Remp: ', (1 - clf2.score(X_train, Y_train)), ' / Rest: ', (1 - clf2.score(X_test, Y_test)))
print('Remp - Rest: ', (1 - clf2.score(X_train, Y_train)) - (1 - clf2.score(X_test, Y_test)))