In [0]:
from tensorflow.keras.datasets import mnist

In [2]:
(x_train, y_train),(x_test, y_test) = mnist.load_data()

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

img_rows, img_cols = 28, 28
input_shape = (img_rows, img_cols, 1)

x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)

print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples


In [0]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, AveragePooling2D # Convolutional layers
from tensorflow.keras.layers import Flatten, Dense, Dropout, Activation # Neural Network layers

In [14]:
model = Sequential([
  Conv2D(28, (4, 4), input_shape=input_shape),
  MaxPool2D((4, 4)),

  Flatten(),
  Dense(128, activation='relu'),
  Dropout(0.2),
  Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

Epoch 1/5
1875/1875 [==============================] - 21s 11ms/step - loss: 0.2008 - accuracy: 0.9392
Epoch 2/5
1875/1875 [==============================] - 26s 14ms/step - loss: 0.0670 - accuracy: 0.9800
Epoch 3/5
1875/1875 [==============================] - 21s 11ms/step - loss: 0.0523 - accuracy: 0.9838
Epoch 4/5
1875/1875 [==============================] - 21s 11ms/step - loss: 0.0402 - accuracy: 0.9876
Epoch 5/5
313/313 [==============================] - 1s 5ms/step - loss: 0.0372 - accuracy: 0.9885


[0.03721008077263832, 0.9884999990463257]

In [56]:
model = Sequential([
  Conv2D(28, (4, 4), activation='relu', input_shape=input_shape),
  AveragePooling2D((2, 2)),
  Conv2D(14, (4, 4)),
  MaxPool2D((2, 2)),

  Flatten(),
  Dense(128, activation='relu'),
  Dropout(0.2),
  Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

Epoch 1/5
1875/1875 [==============================] - 34s 18ms/step - loss: 0.2072 - accuracy: 0.9376
Epoch 2/5
1875/1875 [==============================] - 35s 19ms/step - loss: 0.0669 - accuracy: 0.9795
Epoch 3/5
1875/1875 [==============================] - 35s 19ms/step - loss: 0.0492 - accuracy: 0.9845
Epoch 4/5
1875/1875 [==============================] - 36s 19ms/step - loss: 0.0422 - accuracy: 0.9869
Epoch 5/5
313/313 [==============================] - 2s 7ms/step - loss: 0.0311 - accuracy: 0.9905


[0.031081093475222588, 0.9904999732971191]

# Conclusões

As redes que se utilizam de convoluções apresentaram resultados melhores quando comparadas com as redes neurais que não as utilizam. O resultado obtido anteriormente foi uma acurácia de 97,71% no conjunto de teste.

Com dois modelos de redes neurais convolutivas, os resultados foram: 98.85 e 99.05. Resultados próximos dos listados na seção de redes convolutivas no site do dataset MNIST, onde o pior resultado é de 98.3%.